
name: 'FilecoinStorage'
version: '0.1.0'
description: 'Filecoin Storage client'
homepage: 'https://github.com/rayokaah/filecoin_flutter'
environment:
  sdk: '>=2.12.0 <3.0.0'
dependencies:
  http: '>=0.13.0 <0.14.0'
  intl: '^0.17.0'
  meta: #'^1.1.8'
dev_dependencies:
  test: '>=1.16.0 <1.18.0'
  mocktail:
  build_runner: ^2.3.3
dependency_overrides:
  analyzer: 5.4.0